// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package _go

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Role int32

const (
	Role_UNKNOWN_ROLE   Role = 0
	Role_SERVER_MANAGER Role = 1
	Role_SERVER         Role = 2
	Role_WORKER         Role = 3
)

var Role_name = map[int32]string{
	0: "UNKNOWN_ROLE",
	1: "SERVER_MANAGER",
	2: "SERVER",
	3: "WORKER",
}
var Role_value = map[string]int32{
	"UNKNOWN_ROLE":   0,
	"SERVER_MANAGER": 1,
	"SERVER":         2,
	"WORKER":         3,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}
func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_4868d82887480544, []int{0}
}

// 消息的类型
type Command int32

const (
	Command_UNKNOWN_COMMAND         Command = 0
	Command_ADD_SERVER              Command = 1
	Command_ADD_SERVER_ACK          Command = 2
	Command_INIT_SERVER             Command = 3
	Command_INIT_SERVER_ACK         Command = 4
	Command_DELETE_SERVER           Command = 5
	Command_DELETE_SERVER_ACK       Command = 6
	Command_KEY_RANGE_CHANGE        Command = 7
	Command_KEY_RANGE_CHANGE_ACK    Command = 8
	Command_MASTER_SLAVE_CHANGE     Command = 9
	Command_MASTER_SLAVE_CHANGE_ACK Command = 10
	Command_PULL                    Command = 11
	Command_PULL_ACK                Command = 12
	Command_PUSH                    Command = 13
	Command_PUSH_ACK                Command = 14
	Command_UPDATE                  Command = 15
	Command_UPDATE_ACK              Command = 16
	Command_INC                     Command = 17
	Command_INC_ACK                 Command = 18
	Command_ADD                     Command = 19
	Command_ADD_ACK                 Command = 20
	Command_PING                    Command = 21
	Command_PING_ACK                Command = 22
	Command_CHANGE_SERVER_FINISH    Command = 23
	Command_ADD_WORKER              Command = 24
	Command_SERVER_CHANGE           Command = 25
)

var Command_name = map[int32]string{
	0:  "UNKNOWN_COMMAND",
	1:  "ADD_SERVER",
	2:  "ADD_SERVER_ACK",
	3:  "INIT_SERVER",
	4:  "INIT_SERVER_ACK",
	5:  "DELETE_SERVER",
	6:  "DELETE_SERVER_ACK",
	7:  "KEY_RANGE_CHANGE",
	8:  "KEY_RANGE_CHANGE_ACK",
	9:  "MASTER_SLAVE_CHANGE",
	10: "MASTER_SLAVE_CHANGE_ACK",
	11: "PULL",
	12: "PULL_ACK",
	13: "PUSH",
	14: "PUSH_ACK",
	15: "UPDATE",
	16: "UPDATE_ACK",
	17: "INC",
	18: "INC_ACK",
	19: "ADD",
	20: "ADD_ACK",
	21: "PING",
	22: "PING_ACK",
	23: "CHANGE_SERVER_FINISH",
	24: "ADD_WORKER",
	25: "SERVER_CHANGE",
}
var Command_value = map[string]int32{
	"UNKNOWN_COMMAND":         0,
	"ADD_SERVER":              1,
	"ADD_SERVER_ACK":          2,
	"INIT_SERVER":             3,
	"INIT_SERVER_ACK":         4,
	"DELETE_SERVER":           5,
	"DELETE_SERVER_ACK":       6,
	"KEY_RANGE_CHANGE":        7,
	"KEY_RANGE_CHANGE_ACK":    8,
	"MASTER_SLAVE_CHANGE":     9,
	"MASTER_SLAVE_CHANGE_ACK": 10,
	"PULL":                 11,
	"PULL_ACK":             12,
	"PUSH":                 13,
	"PUSH_ACK":             14,
	"UPDATE":               15,
	"UPDATE_ACK":           16,
	"INC":                  17,
	"INC_ACK":              18,
	"ADD":                  19,
	"ADD_ACK":              20,
	"PING":                 21,
	"PING_ACK":             22,
	"CHANGE_SERVER_FINISH": 23,
	"ADD_WORKER":           24,
	"SERVER_CHANGE":        25,
}

func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}
func (Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_message_4868d82887480544, []int{1}
}

// 服务器节点
type Node struct {
	Index                int32    `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Ready                bool     `protobuf:"varint,3,opt,name=Ready,proto3" json:"Ready,omitempty"`
	Role                 Role     `protobuf:"varint,4,opt,name=Role,proto3,enum=communicate.Role" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_4868d82887480544, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Node) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Node) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func (m *Node) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_UNKNOWN_ROLE
}

// key的范围
type Range struct {
	Begin                int32    `protobuf:"varint,1,opt,name=Begin,proto3" json:"Begin,omitempty"`
	End                  int32    `protobuf:"varint,2,opt,name=End,proto3" json:"End,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Range) Reset()         { *m = Range{} }
func (m *Range) String() string { return proto.CompactTextString(m) }
func (*Range) ProtoMessage()    {}
func (*Range) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_4868d82887480544, []int{1}
}
func (m *Range) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Range.Unmarshal(m, b)
}
func (m *Range) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Range.Marshal(b, m, deterministic)
}
func (dst *Range) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Range.Merge(dst, src)
}
func (m *Range) XXX_Size() int {
	return xxx_messageInfo_Range.Size(m)
}
func (m *Range) XXX_DiscardUnknown() {
	xxx_messageInfo_Range.DiscardUnknown(m)
}

var xxx_messageInfo_Range proto.InternalMessageInfo

func (m *Range) GetBegin() int32 {
	if m != nil {
		return m.Begin
	}
	return 0
}

func (m *Range) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

// 多台服务器节点
type Nodes struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_4868d82887480544, []int{2}
}
func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (dst *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(dst, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

// Server Cluster信息
type Cluster struct {
	// 下面是4个长度相同的数组，各位置的上信息一一对应
	Servers              []*Node  `protobuf:"bytes,1,rep,name=Servers,proto3" json:"Servers,omitempty"`
	RangeEnd             []int32  `protobuf:"varint,2,rep,packed,name=RangeEnd,proto3" json:"RangeEnd,omitempty"`
	Masters              []*Nodes `protobuf:"bytes,3,rep,name=Masters,proto3" json:"Masters,omitempty"`
	Slaves               []*Nodes `protobuf:"bytes,4,rep,name=Slaves,proto3" json:"Slaves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_4868d82887480544, []int{3}
}
func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (dst *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(dst, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetServers() []*Node {
	if m != nil {
		return m.Servers
	}
	return nil
}

func (m *Cluster) GetRangeEnd() []int32 {
	if m != nil {
		return m.RangeEnd
	}
	return nil
}

func (m *Cluster) GetMasters() []*Nodes {
	if m != nil {
		return m.Masters
	}
	return nil
}

func (m *Cluster) GetSlaves() []*Nodes {
	if m != nil {
		return m.Slaves
	}
	return nil
}

// 一个Key对应的Value是一个数组
type Value struct {
	Values               []float64 `protobuf:"fixed64,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_4868d82887480544, []int{4}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

// 消息
type Message struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Sender               *Node    `protobuf:"bytes,2,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver             *Node    `protobuf:"bytes,3,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	ServerClusterInfo    *Cluster `protobuf:"bytes,4,opt,name=ServerClusterInfo,proto3" json:"ServerClusterInfo,omitempty"`
	KeyRange             *Range   `protobuf:"bytes,5,opt,name=KeyRange,proto3" json:"KeyRange,omitempty"`
	Values               []*Value `protobuf:"bytes,6,rep,name=Values,proto3" json:"Values,omitempty"`
	Command              Command  `protobuf:"varint,7,opt,name=Command,proto3,enum=communicate.Command" json:"Command,omitempty"`
	RespondMsgId         int64    `protobuf:"varint,8,opt,name=RespondMsgId,proto3" json:"RespondMsgId,omitempty"`
	RespondSuccess       bool     `protobuf:"varint,9,opt,name=RespondSuccess,proto3" json:"RespondSuccess,omitempty"`
	DeleteNode           *Node    `protobuf:"bytes,10,opt,name=DeleteNode,proto3" json:"DeleteNode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_4868d82887480544, []int{5}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetSender() *Node {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *Message) GetReceiver() *Node {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *Message) GetServerClusterInfo() *Cluster {
	if m != nil {
		return m.ServerClusterInfo
	}
	return nil
}

func (m *Message) GetKeyRange() *Range {
	if m != nil {
		return m.KeyRange
	}
	return nil
}

func (m *Message) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Message) GetCommand() Command {
	if m != nil {
		return m.Command
	}
	return Command_UNKNOWN_COMMAND
}

func (m *Message) GetRespondMsgId() int64 {
	if m != nil {
		return m.RespondMsgId
	}
	return 0
}

func (m *Message) GetRespondSuccess() bool {
	if m != nil {
		return m.RespondSuccess
	}
	return false
}

func (m *Message) GetDeleteNode() *Node {
	if m != nil {
		return m.DeleteNode
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "communicate.Node")
	proto.RegisterType((*Range)(nil), "communicate.Range")
	proto.RegisterType((*Nodes)(nil), "communicate.Nodes")
	proto.RegisterType((*Cluster)(nil), "communicate.Cluster")
	proto.RegisterType((*Value)(nil), "communicate.Value")
	proto.RegisterType((*Message)(nil), "communicate.Message")
	proto.RegisterEnum("communicate.Role", Role_name, Role_value)
	proto.RegisterEnum("communicate.Command", Command_name, Command_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_4868d82887480544) }

var fileDescriptor_message_4868d82887480544 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xed, 0x6e, 0xda, 0x58,
	0x10, 0x8d, 0x31, 0xc6, 0xce, 0x40, 0xc8, 0x65, 0x42, 0x12, 0xef, 0xee, 0x8f, 0x45, 0x48, 0xbb,
	0xcb, 0x66, 0x77, 0xd9, 0x36, 0x7d, 0x02, 0x07, 0xbb, 0x60, 0x01, 0x26, 0xba, 0x26, 0x89, 0xfa,
	0x0b, 0xb9, 0xf8, 0x16, 0x45, 0x02, 0x3b, 0xc2, 0x10, 0x35, 0xef, 0xd4, 0xa7, 0xa8, 0xd4, 0xf7,
	0xaa, 0xee, 0xd8, 0xa6, 0x81, 0x90, 0xfe, 0xca, 0xcc, 0x39, 0x67, 0x3e, 0xee, 0x19, 0x07, 0x38,
	0x5a, 0x88, 0x24, 0x09, 0x66, 0xa2, 0xfd, 0xb0, 0x8c, 0x57, 0x31, 0x96, 0xa7, 0xf1, 0x62, 0xb1,
	0x8e, 0xee, 0xa7, 0xc1, 0x4a, 0x34, 0x17, 0x50, 0xf4, 0xe2, 0x50, 0x60, 0x1d, 0x34, 0x37, 0x0a,
	0xc5, 0x67, 0x53, 0x69, 0x28, 0x2d, 0x8d, 0xa7, 0x09, 0x22, 0x14, 0x7b, 0x71, 0xb2, 0x32, 0x0b,
	0x0d, 0xa5, 0x75, 0xc8, 0x29, 0x96, 0x4a, 0x2e, 0x82, 0xf0, 0xc9, 0x54, 0x1b, 0x4a, 0xcb, 0xe0,
	0x69, 0x82, 0x7f, 0x40, 0x91, 0xc7, 0x73, 0x61, 0x16, 0x1b, 0x4a, 0xab, 0x7a, 0x59, 0x6b, 0x3f,
	0x9b, 0xd1, 0x96, 0x04, 0x27, 0xba, 0xf9, 0x3f, 0x68, 0x3c, 0x88, 0x66, 0x34, 0xef, 0x4a, 0xcc,
	0xee, 0xa3, 0x7c, 0x1e, 0x25, 0xc8, 0x40, 0x75, 0xa2, 0x90, 0xc6, 0x69, 0x5c, 0x86, 0xcd, 0x37,
	0xa0, 0xc9, 0xfd, 0x12, 0xfc, 0x2b, 0x0b, 0x4c, 0xa5, 0xa1, 0xb6, 0xca, 0x3b, 0x13, 0x24, 0xc3,
	0x53, 0xbe, 0xf9, 0x45, 0x01, 0xbd, 0x33, 0x5f, 0x27, 0x2b, 0xb1, 0xc4, 0x7f, 0x40, 0xf7, 0xc5,
	0xf2, 0x51, 0x2c, 0x7f, 0x52, 0x96, 0x2b, 0xf0, 0x57, 0x30, 0x68, 0xb7, 0x74, 0x03, 0xb5, 0xa5,
	0xf1, 0x4d, 0x8e, 0xff, 0x82, 0x3e, 0x0c, 0x64, 0xcb, 0xc4, 0x54, 0xa9, 0x11, 0xbe, 0x68, 0x94,
	0xf0, 0x5c, 0x82, 0x17, 0x50, 0xf2, 0xe7, 0xc1, 0xa3, 0x48, 0xcc, 0xe2, 0xab, 0xe2, 0x4c, 0xd1,
	0xfc, 0x1d, 0xb4, 0xdb, 0x60, 0xbe, 0x16, 0x78, 0x06, 0x25, 0x0a, 0xd2, 0x55, 0x15, 0x9e, 0x65,
	0xcd, 0xaf, 0x2a, 0xe8, 0xc3, 0xf4, 0x80, 0x58, 0x85, 0x82, 0x1b, 0x92, 0x65, 0x2a, 0x2f, 0xb8,
	0x21, 0xfe, 0x0d, 0x25, 0x5f, 0x44, 0xa1, 0x58, 0x92, 0x65, 0x7b, 0x9f, 0x97, 0x09, 0xf0, 0x3f,
	0x30, 0xb8, 0x98, 0x8a, 0xfb, 0x47, 0xb1, 0xa4, 0xcb, 0xed, 0x15, 0x6f, 0x24, 0x78, 0x05, 0xb5,
	0xd4, 0x97, 0xcc, 0x4a, 0x37, 0xfa, 0x14, 0xd3, 0x71, 0xcb, 0x97, 0xf5, 0xad, 0xba, 0x8c, 0xe7,
	0x2f, 0xe5, 0xd8, 0x06, 0xa3, 0x2f, 0x9e, 0xc8, 0x43, 0x53, 0xa3, 0xd2, 0x6d, 0x23, 0x88, 0xe1,
	0x1b, 0x8d, 0xb4, 0x2d, 0x73, 0xa0, 0xb4, 0xc7, 0x36, 0xa2, 0x72, 0x57, 0xb0, 0x0d, 0x7a, 0x27,
	0x5e, 0x2c, 0x82, 0x28, 0x34, 0x75, 0xfa, 0xe4, 0x76, 0xb6, 0x4a, 0x39, 0x9e, 0x8b, 0xb0, 0x09,
	0x15, 0x2e, 0x92, 0x87, 0x38, 0x0a, 0x87, 0xc9, 0xcc, 0x0d, 0x4d, 0x83, 0x3c, 0xdc, 0xc2, 0xf0,
	0x4f, 0xa8, 0x66, 0xb9, 0xbf, 0x9e, 0x4e, 0x45, 0x92, 0x98, 0x87, 0xf4, 0x89, 0xef, 0xa0, 0xf8,
	0x16, 0xc0, 0x16, 0x73, 0xb1, 0x12, 0xd2, 0x33, 0x13, 0x5e, 0x33, 0xf3, 0x99, 0xe8, 0xc2, 0x4e,
	0xff, 0x3d, 0x90, 0x41, 0xe5, 0xc6, 0xeb, 0x7b, 0xa3, 0x3b, 0x6f, 0xc2, 0x47, 0x03, 0x87, 0x1d,
	0x20, 0x42, 0xd5, 0x77, 0xf8, 0xad, 0xc3, 0x27, 0x43, 0xcb, 0xb3, 0xba, 0x0e, 0x67, 0x0a, 0x02,
	0x94, 0x52, 0x8c, 0x15, 0x64, 0x7c, 0x37, 0xe2, 0x7d, 0x87, 0x33, 0xf5, 0xe2, 0x9b, 0xba, 0x79,
	0x35, 0x9e, 0xc0, 0x71, 0xde, 0xa9, 0x33, 0x1a, 0x0e, 0x2d, 0xcf, 0x66, 0x07, 0x58, 0x05, 0xb0,
	0x6c, 0x7b, 0x92, 0x15, 0x2b, 0xb2, 0xf9, 0x8f, 0x7c, 0x62, 0x75, 0xfa, 0xac, 0x80, 0xc7, 0x50,
	0x76, 0x3d, 0x77, 0x9c, 0x8b, 0x54, 0xd9, 0xe9, 0x19, 0x40, 0xaa, 0x22, 0xd6, 0xe0, 0xc8, 0x76,
	0x06, 0xce, 0xd8, 0xc9, 0x75, 0x1a, 0x9e, 0x42, 0x6d, 0x0b, 0x22, 0x65, 0x09, 0xeb, 0xc0, 0xfa,
	0xce, 0x87, 0x09, 0xb7, 0xbc, 0xae, 0x33, 0xe9, 0xf4, 0xe4, 0x1f, 0xa6, 0xa3, 0x09, 0xf5, 0x5d,
	0x94, 0xf4, 0x06, 0x9e, 0xc3, 0xc9, 0xd0, 0xf2, 0xc7, 0x0e, 0x9f, 0xf8, 0x03, 0xeb, 0x76, 0x53,
	0x72, 0x88, 0xbf, 0xc1, 0xf9, 0x1e, 0x82, 0xaa, 0x00, 0x0d, 0x28, 0x5e, 0xdf, 0x0c, 0x06, 0xac,
	0x8c, 0x15, 0x30, 0x64, 0x44, 0x78, 0x25, 0xc5, 0xfd, 0x1e, 0x3b, 0x4a, 0x71, 0xbf, 0x47, 0x78,
	0x55, 0xda, 0x76, 0x73, 0x6d, 0x5b, 0x63, 0x87, 0x1d, 0x4b, 0x57, 0xd2, 0x98, 0x38, 0x86, 0x3a,
	0xa8, 0xae, 0xd7, 0x61, 0x35, 0x2c, 0x83, 0xee, 0x7a, 0x1d, 0x42, 0x51, 0xa2, 0x96, 0x6d, 0xb3,
	0x13, 0x89, 0x4a, 0xd3, 0x24, 0x5a, 0xa7, 0xfe, 0xae, 0xd7, 0x65, 0xa7, 0xd4, 0xdf, 0xf5, 0xba,
	0x84, 0x9f, 0xc9, 0xf7, 0x65, 0xfb, 0x65, 0x66, 0xbc, 0x77, 0x3d, 0xd7, 0xef, 0xb1, 0xf3, 0xfc,
	0x06, 0xd9, 0xd1, 0x4c, 0xe9, 0x64, 0x26, 0xc9, 0x5e, 0xfa, 0xcb, 0xc7, 0x12, 0xfd, 0x10, 0xbf,
	0xfb, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x95, 0xd8, 0xb7, 0x99, 0x05, 0x00, 0x00,
}
